/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Acer
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new Background();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(925, 730));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Impartida por:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Luis Móran");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("La estadistica es la ciencia que estudia la recolección, análisis e interpretación de datos para obtener");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 896, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("concluciones y tomar decisiones informadas. Se divide en dos ramas: la estaditica descriptiva, que resume y ");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 896, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("presenta datos mediante medidas como la media, la desviación estándar; y la estadística inferencial, que ");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 896, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("permite hacer generalizaciones sobre una población a partir de una muestra, usando probabilidad e intervalos");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, 919, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("de confianza. Esta disciplina es esencial en áreas como ciencias, economía y medicina, donde ayuda a entender y ");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 201, 919, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("predecir fenémenos complejos");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, 919, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("ESTADISTICA I");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("ING. LUIS GOMEZ");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("\"Y conoceréis la verdad y la verdad os hará libres\"");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 400, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luisgomez.png"))); // NOI18N
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 381, 110, 143));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fernando.png"))); // NOI18N
        jLabel15.setText("jLabel12");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 110, 143));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luisgomez.png"))); // NOI18N
        jLabel16.setText("jLabel12");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 368, 110, 140));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alejandro.png"))); // NOI18N
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 110, 130));

        jLabel2.setText("2690-23-1563");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Alejandro Cabrera ");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, -1, -1));

        jLabel18.setText("2690-23-11913");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Cristian Ajxup ");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        jLabel20.setText("2690-21-15800");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, -1, -1));

        jLabel21.setText("forma clara y fácil de seguir.\"");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 170, -1));

        jLabel22.setText("Docente en URL, CUNOC, UMG");
        bg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel23.setText("\"Excelente curso, presenta los");
        bg.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 180, -1));

        jLabel24.setText("conceptos de estadistica de");
        bg.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 170, -1));

        jLabel25.setText("\"Gran curso, logra que temas");
        bg.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 170, -1));

        jLabel26.setText("avanzados de estadistica sean");
        bg.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 170, -1));

        jLabel27.setText("faciles de entender.\"");
        bg.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 170, -1));

        jLabel28.setText("\"El contenido es preciso y útil,");
        bg.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 170, -1));

        jLabel29.setText("ideal para cosntruir una base");
        bg.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 170, -1));

        jLabel30.setText("sólida en estadistica.\"");
        bg.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 170, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel31.setText("Comentarios positivos:");
        bg.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 252, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    class Background extends JPanel{
        private Image imagen;
        
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/bg_content.png")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
