

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */


import java.awt.BorderLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luism
 */
public class InputDataDialog extends javax.swing.JDialog {
     private JTable table;
    private DefaultTableModel tableModel;
    private JButton addButton;
    private JButton confirmButton;
    /**
     * Creates new form InputDataDialog
     */
    public InputDataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, "Ingrese datos", true);
        
        // Configuración del modelo de la tabla
        tableModel = new DefaultTableModel(new String[]{"Clase", "Frecuencia"}, 0);
        table = new JTable(tableModel);
        
        // Botón para agregar filas
        addButton = new JButton("Agregar Fila");
        addButton.addActionListener(e -> addRow());
        
        // Botón para confirmar los datos
        confirmButton = new JButton("Confirmar");
        confirmButton.addActionListener(e -> confirmData());
        
        // Agregar componentes al dialog
        setLayout(new BorderLayout());
        add(new JScrollPane(table), BorderLayout.CENTER);
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(addButton);
        buttonPanel.add(confirmButton);
        add(buttonPanel, BorderLayout.SOUTH);
        
        setSize(400, 300);
        setLocationRelativeTo(parent);
    }

    private void addRow() {
        tableModel.addRow(new Object[]{"", ""}); // Agrega una fila vacía
    }

    private void confirmData() {
        // Aquí puedes procesar los datos ingresados
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String clase = (String) tableModel.getValueAt(i, 0);
            String frecuencia = (String) tableModel.getValueAt(i, 1);
            System.out.println("Clase: " + clase + ", Frecuencia: " + frecuencia);
        }
        dispose(); // Cierra el dialog
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            JFrame frame = new JFrame("Demo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JButton openDialogButton = new JButton("Abrir Diálogo");
        openDialogButton.addActionListener(e -> {
            InputDataDialog dialog = new InputDataDialog(frame, true);
            dialog.setVisible(true);
        });
        frame.add(openDialogButton);
        frame.setSize(300, 200);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

            }
        });

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
