/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import Classes.Formulas;
import java.awt.Graphics;
import java.awt.Image;
import java.math.BigInteger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Acer
 */
public class tema6 extends javax.swing.JPanel {

   
    //Metodo Main temporal para hacer pruebas 
    public static void main(String[] args) {
        
        JFrame frame = new JFrame("Prueba de Frame");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(925, 730);
        tema6 panel = new tema6(); //cambiar "tema6" por nombre del panel 
        
        frame.add(panel);
        
        frame.setVisible(true); 
    }
    
    
    public tema6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
=======
        bg = new Background();
>>>>>>> a7e80c1 (Diseño de pestañas e implementación en el Dashboard)
        txtResulPermutacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorN = new javax.swing.JTextField();
        btnTeorema4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtValoresN = new javax.swing.JTextField();
        btnPermutacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResulTeorema4 = new javax.swing.JTextField();
        txtResulCombinacion = new javax.swing.JTextField();
        btnCombinacion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtValorR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(925, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setToolTipText("[255,255,255");
        bg.setPreferredSize(new java.awt.Dimension(925, 730));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResulPermutacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtResulPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResulPermutacionActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        bg.add(txtResulPermutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 220, 30));
=======
        bg.add(txtResulPermutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 190, 50));
>>>>>>> a7e80c1 (Diseño de pestañas e implementación en el Dashboard)

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Separados por comas ");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 120, 30));

        txtValorN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bg.add(txtValorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 90, 30));

        btnTeorema4.setBackground(new java.awt.Color(7, 87, 91));
        btnTeorema4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTeorema4.setForeground(new java.awt.Color(255, 255, 255));
        btnTeorema4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconCalculator.png"))); // NOI18N
        btnTeorema4.setText("Calcular");
        btnTeorema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeorema4ActionPerformed(evt);
            }
        });
        bg.add(btnTeorema4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 150, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Permutacion de N objetos:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 320, 30));

        txtValoresN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bg.add(txtValoresN, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 150, 30));

        btnPermutacion.setBackground(new java.awt.Color(7, 87, 91));
        btnPermutacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPermutacion.setForeground(new java.awt.Color(255, 255, 255));
        btnPermutacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconCalculator.png"))); // NOI18N
        btnPermutacion.setText("Calcular");
        btnPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermutacionActionPerformed(evt);
            }
        });
        bg.add(btnPermutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 150, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Valor \"r\":");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Permutacion:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 160, 30));

        txtResulTeorema4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtResulTeorema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResulTeorema4ActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        bg.add(txtResulTeorema4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 220, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Resultado:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 90, 30));

        txtResulCombinacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bg.add(txtResulCombinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 220, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Resultado:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 90, 30));
=======
        bg.add(txtResulTeorema4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 190, 50));

        txtResulCombinacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bg.add(txtResulCombinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 160, 50));
>>>>>>> a7e80c1 (Diseño de pestañas e implementación en el Dashboard)

        btnCombinacion.setBackground(new java.awt.Color(7, 87, 91));
        btnCombinacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCombinacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCombinacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconCalculator.png"))); // NOI18N
        btnCombinacion.setText("Calcular");
        btnCombinacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinacionActionPerformed(evt);
            }
        });
        bg.add(btnCombinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 130, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Combinación:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 160, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Valor de \"n\":");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));

        txtValorR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bg.add(txtValorR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 90, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Valores para N objetos:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 190, 30));

        jLabel13.setFont(new java.awt.Font("SimSun", 0, 48)); // NOI18N
        jLabel13.setText("TEMA 6");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("<html>Determinar cantidad de intervalos, Amplitud de los intervalos</html> ");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Calculadora de Problemas");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtResulPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResulPermutacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResulPermutacionActionPerformed

    private void btnPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermutacionActionPerformed
        int valorN = Integer.parseInt(txtValorN.getText());
        int valorR = Integer.parseInt(txtValorR.getText());

        Formulas formula = new Formulas();
        BigInteger resultado = formula.permutacion(valorN, valorR);
        txtResulPermutacion.setText(resultado.toString());
        
    }//GEN-LAST:event_btnPermutacionActionPerformed

    private void txtResulTeorema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResulTeorema4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResulTeorema4ActionPerformed

    private void btnCombinacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinacionActionPerformed
        int valorN = Integer.parseInt(txtValorN.getText());
        int valorR = Integer.parseInt(txtValorR.getText());
        
        Formulas formula = new Formulas();
        BigInteger resultado = formula.combinacion(valorN, valorR);
        txtResulCombinacion.setText(resultado.toString());
    }//GEN-LAST:event_btnCombinacionActionPerformed

    private void btnTeorema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeorema4ActionPerformed
      
        Formulas formula = new Formulas();
    try {
               
                int n = Integer.parseInt(txtValorN.getText());
                
                // Obtener los valores de las clases separados por comas
                String[] partes = txtValoresN.getText().split(",");
                int[] clases = new int[partes.length];
                
                for (int i = 0; i < partes.length; i++) {
                    clases[i] = Integer.parseInt(partes[i].trim());
                }

                // Verificar que la suma de las clases sea igual o menor a n
                int sumaClases = 0;
                for (int clase : clases) {
                    sumaClases += clase;
                }

                if (sumaClases > n) {
                    txtResulTeorema4.setText("Error: Suma mayor a n");
                    
                } else {
                    // Calcular el resultado
                    BigInteger resultado = formula.permutacionConClases(n, clases);
                    txtResulTeorema4.setText(resultado.toString());
                }
            } catch (NumberFormatException ex) {
                txtResulTeorema4.setText("Ingrese números válidos.");
            }
    }//GEN-LAST:event_btnTeorema4ActionPerformed

    class Background extends JPanel{
        private Image imagen;
        
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/bg_content.png")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCombinacion;
    private javax.swing.JButton btnPermutacion;
    private javax.swing.JButton btnTeorema4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtResulCombinacion;
    private javax.swing.JTextField txtResulPermutacion;
    private javax.swing.JTextField txtResulTeorema4;
    private javax.swing.JTextField txtValorN;
    private javax.swing.JTextField txtValorR;
    private javax.swing.JTextField txtValoresN;
    // End of variables declaration//GEN-END:variables
}
